// 对首屏性能有要求的话，可以在使用的页面引入
import {
  Button,
  Icon,
  FormModel,
  Input,
  Radio,
  Card,
  Menu,
  Layout,
  Space,
  Breadcrumb,
  Table,
  Spin,
  Avatar,
  Dropdown,
  message,
  Row,
  Col,
  Select,
  ConfigProvider,
  Checkbox,
  Badge,
  Tooltip,
  Modal,
  Form,
  Steps,
  Popover,
  Cascader,
  Timeline,
  DatePicker,
  Popconfirm,
  Anchor,
  Upload,
  Tabs,
  InputNumber,
  Tag,
  Tree,
  List,
  Divider,
  Descriptions,
  Drawer,
  Carousel,
  AutoComplete,
  Switch,
  Result
} from 'ant-design-vue';
import '@/assets/styles/rewrite.less';
export default (Vue) => {
  Vue.use(Button);
  Vue.use(Icon);
  Vue.use(FormModel);
  Vue.use(Input);
  Vue.use(Radio);
  Vue.use(Card);
  Vue.use(Menu);
  Vue.use(Layout);
  Vue.use(Space);
  Vue.use(Breadcrumb);
  Vue.use(Table);
  Vue.use(Spin);
  Vue.use(Avatar);
  Vue.use(Dropdown);
  Vue.use(Row);
  Vue.use(Col);
  Vue.use(Select);
  Vue.use(ConfigProvider);
  Vue.use(Checkbox);
  Vue.use(Badge);
  Vue.use(Tooltip);
  Vue.use(Modal);
  Vue.use(Steps);
  Vue.use(Form);
  Vue.use(Popover);
  Vue.use(Cascader);
  Vue.use(Timeline);
  Vue.use(DatePicker);
  Vue.use(Popconfirm);
  Vue.use(Anchor);
  Vue.use(Upload);
  Vue.use(Tabs);
  Vue.use(InputNumber);
  Vue.use(Tag);
  Vue.use(List);
  Vue.use(Divider);
  Vue.use(Tree);
  Vue.use(Descriptions);
  Vue.use(Drawer);
  Vue.use(Carousel);
  Vue.use(AutoComplete);
  Vue.use(Switch);
  Vue.use(Result);
  Vue.prototype.$message = message;
  Vue.prototype.$modal = Modal;
};
